language: python

jobs:
  include:
    - os: linux
      python: 3.7
    - os: osx
      python: 3.7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
before_install:
  - if [ "TRAVIS_OS_NAME" = "linux"]; then export CC=gcc-5; fi
  - if [ "TRAVIS_OS_NAME" = "linux"]; then export CXX=g++-5; fi
  - if [ "TRAVIS_OS_NAME" = "osx"]; then export MACOSX_DEPLOYMENT_TARGET=10.9; fi
  - if [ "TRAVIS_OS_NAME" = "osx"]; then export CC=clang; fi
  - if [ "TRAVIS_OS_NAME" = "osx"]; then export CXX=clang++; fi
install:
  - pip install numpy
  - pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - pip install pycodestyle
  - pip install flake8
  - pip install codecov
  - pip install sphinx
  - pip install sphinx_rtd_theme
script:
  - python -c "import torch; print(torch.__version__)"
  - pycodestyle .
  - flake8 .
  - python setup.py install
  - python setup.py test
  - cd docs && make clean && make html && make doctest && cd ..
after_success:
  - codecov
notifications:
  email: false
