language: python

jobs:
  include:
    - os: linux
      python: 3.7
      before_install:
        - export CC=gcc-5
        - export CXX=g++-5
    - os: osx
      osx_image: xcode10.2
      python: 3.7
      before_install:
        - export MACOSX_DEPLOYMENT_TARGET=10.9
        - export CC=clang
        - export CXX=clang++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
install:
  - pip install numpy
  - pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - pip install pycodestyle
  - pip install flake8
  - pip install codecov
  - pip install sphinx
  - pip install sphinx_rtd_theme
script:
  - python -c "import torch; print(torch.__version__)"
  - pycodestyle .
  - flake8 .
  - python setup.py install
  - python setup.py test
  - cd docs && make clean && make html && make doctest && cd ..
after_success:
  - codecov
notifications:
  email: false
